### ISSUE TITLE
[FEATURE]: Dark Mode with Toggle Button

### ISSUE THREAD

**Issue by Vijaykv5** [vatsalsinghkv/easy-fix#1]
It would be good, if we add an toggle button for Dark and Light theme

**Comment by harshmangalam** [comment]
Okay i will add please assign this to me

**Comment by vatsalsinghkv** [comment]
@harshmangalam I'll be assigning issues at the start of the hacktoberfest. Feel free to explore the project for further features and issues.

**Comment by vatsalshah041** [comment]
can you assign the issue to me for adding the toggle for light and dark theme

**Comment by Babunshil** [comment]
Sir I want to work on this can you assign ne it under hacktoberfest 2023

**Comment by paragpurandare** [comment]
Hi vastalshah , i have gone through your project codebase and would like to contribute to it in hacktoberfest

**Comment by paragpurandare** [comment]
Hi @vatsalsinghkv i have gone through your project codebase and would like to contribute to it under hacktoberfest 2023

**Comment by Shivansh175** [comment]
Hello @vatsalsinghkv will u please assign me this issue?

**Comment by vatsalsinghkv** [comment]
Hey @paragpurandare @Shivansh175 @Babunshil, do you guys have an approach for implementing this feature? like using custom hook like `useTheme()` for managing dark n light mode and storing it into the local storage so it won't change on refreshing and having device-prefered theme initially

**Comment by DhairyaMajmudar** [comment]
@vatsalshah041 I would like to implement this issue. As I inspected the website it seems that it is using Tailwind CSS, I will be using the " dark: " property of Tailwind CSS along with the useEffect Hook to toggle between dark and light modes

**Comment by anxbt** [comment]
![Screenshot 2023-09-30 095517](https://github.com/vatsalsinghkv/easy-fix/assets/127748618/f4dbeaca-3ef4-420d-9443-586a34c3b179)
Assign me this.As i already implemented the basic logic now I'm tryoing to polish it.

**Comment by vatsalsinghkv** [comment]
Hey @Babunshil , you're approach is nice but adding `dark:` everywhere is gonna get irrelevant. So I want you do this approach instead:
- Create a class based dark theme. 
- Create css variables for dark and light themes (like --color-text), and then use them in tailwindCSS config file `colors: { primary: var(--color-primary) }`.
- Write a logic for toggling `dark` class on html and storing the theme (isDark) in local storage. You can create a custom hook (`hooks/useTheme.tsx` or something).
- Even you can improve it by having a default theme (for the first time users or when theme is not stored in local storage) as user's device theme, if you find it hard take dark theme as the default.

If you need any help or have any doubt you can even discuss to me in our [Discord](https://discord.gg/MwBrwVaxmu)

**Comment by DhairyaMajmudar** [comment]
Thank you @vatsalsinghkv for assigning me this issue. I will surely consider the above advice to implement the feature

**Comment by vatsalsinghkv** [comment]
@DhairyaMajmudar sure just let me know if you need any help. Happy coding❤️
