### ISSUE TITLE
[FEATURE] Migrate Components to TypeScript

### ISSUE THREAD

**Issue by vatsalsinghkv** [vatsalsinghkv/easy-fix#10]
### Description

- Migrate `src/components/*.jsx` to `*.tsx`,
- Also add data fetch response type in `utils/type.ts`

### ✨ Browser

Google Chrome

### Checklist 🚀

- [X] I checked and didn't find similar [issue](https://github.com/vatsalsinghkv/easy-fix/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/vatsalsinghkv/easy-fix/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (blank for no).

**Comment by hitesh-wadile** [comment]
Hey @vatsalsinghkv ,

I ready to work on this Isuue. If it not assigned to anyone yet. 👍

**Comment by premtw** [comment]
Hi @vatsalsinghkv 
   I like to contribute to this issue. Please assign to me

**Comment by vatsalsinghkv** [comment]
@hitesh-wadile How's the progress you can check the #17 to work accordingly

**Comment by hitesh-wadile** [comment]
Ya for Sure.

**Comment by vatsalsinghkv** [comment]
@hitesh-wadile how's the progress?

**Comment by hitesh-wadile** [comment]
I am done with 5 Components. Soon I will Complete it.

**Comment by vatsalsinghkv** [comment]
@hitesh-wadile sure just let me know if you need any help

**Comment by hitesh-wadile** [comment]
@vatsalsinghkv for sure. I will let you know if required.

**Comment by hitesh-wadile** [comment]
@vatsalsinghkv  Can you assigned this issue to other person. I getting delayed with my work. Sorry to inform you but I dont want to waste your time. You can unassigned me.
