### ISSUE TITLE
[OTHER] Adding CODE_OF_CONDUCT.md file

### ISSUE THREAD

**Issue by sb-decoder** [vatsalsinghkv/easy-fix#14]
### What would you like to share?

I will be adding CODE_OF_CONDUCT.md file to your repo

### ✨ Browser

Google Chrome

### Checklist 🚀

- [X] I checked and didn't find similar [issue](https://github.com/vatsalsinghkv/easy-fix/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/vatsalsinghkv/easy-fix/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no).

**Comment by sb-decoder** [comment]
please assign me this task under hacktoberfest

**Comment by vatsalsinghkv** [comment]
@sb-decoder Sure, you're got good eyes for the detail ❤️

**Comment by vatsalsinghkv** [comment]
@sb-decoder how's the progress

**Comment by rishuxd** [comment]
Hey @vatsalsinghkv, do we actually need this!
If yes, I will take refs from other repos and make one for us too. What do you say?

**Comment by vatsalsinghkv** [comment]
@rishuxd I am not sure but you can check other open source projects for the references

**Comment by rishuxd** [comment]
@vatsalsinghkv Okay, I'll add this up soon.

**Comment by rishuxd** [comment]
Hey @vatsalsinghkv, I have raised the PR for this. Please take a look. I have reviewed the CODE OF CONDUCT from popular repositories such as freeCodeCamp and Axios, and I've used GitHub's template with the necessary modifications.
