### ISSUE TITLE
[FEATURE] Improve file structure

### ISSUE THREAD

**Issue by vatsalsinghkv** [vatsalsinghkv/easy-fix#22]
### Description

Introduce `src/lib/` dir, and put all the api/ hooks/ & utils/ files init

### ✨ Browser

Google Chrome

### Checklist 🚀

- [X] I checked and didn't find similar [issue](https://github.com/vatsalsinghkv/easy-fix/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/vatsalsinghkv/easy-fix/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (blank for no).

**Comment by HarshMakadiya** [comment]
hey, there can you please assign it to me?

**Comment by IIB3nceII** [comment]
@vatsalsinghkv please assign it to me as we disgussed earlier
