### ISSUE TITLE
[FEATURE] Adopting a Weight-based ranking of issues when they are rendered

### ISSUE THREAD

**Issue by zakhaev26** [vatsalsinghkv/easy-fix#26]
### Description

Currently the Application lists the Issues according to :
- Best-Match
- Comments
- Reactions
- Updated

However, there are many issues that have already been assigned by maintainers to someone. To enhance the usability of the app, it would be more helpful to prioritize issues that don't have an assigned label. We can achieve this by implementing some sort of weighting mechanism that will ensure these unlabeled issues receive greater visibility on the screen.

### ✨ Browser

Google Chrome

### Checklist 🚀

- [X] I checked and didn't find similar [issue](https://github.com/vatsalsinghkv/easy-fix/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/vatsalsinghkv/easy-fix/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no).

**Comment by zakhaev26** [comment]
@vatsalsinghkv Removing them would be a bad option, imo.

There might be issues which are assigned to someone, maybe in process of solving it / has already a PR referencing to that issue. But there might be a case where issue assigned to someone is not being handled properly by them. Maintainer might not pay heed to this for some time , but if there is someone willing to actively contribute to that ,it just resolves it faster. 

I have not looked into Github API as of now, but one way I am thinking of implementing this is keeping separate calls for assigned issues and placing them at around the lower pages(~97-100ish).That way more weight will be given to unassigned issues.

Let me know if this sounds good

**Comment by vatsalsinghkv** [comment]
@zakhaev26  nice one, i didn't consider that, can do that. But I think github api provides the data how are the assigns on the issue, but feel free to approach the problem as you see fit
