### ISSUE TITLE
[FEATURE] Add more filtering options

### ISSUE THREAD

**Issue by newtoallofthis123** [vatsalsinghkv/easy-fix#3]
### Description

The current website provides a very clean to use interface to find GitHub issues. 

However, it has very less filtering options. By filtering options, I mean the following

1. Ability to filter more languages
2. Filter by User 
3. Custom Filters

I believe that I can add and create the filters. Here is how I would do so:
- Use the GitHub API to get the repos based on issues, then hold all the languages used by them in a hook and display it on the filter bar
- Same as above, I would also add filter by user
- GitHub also allows us to filter by writing a query in this syntax [`is:issue is:open sort:updated-desc label:hacktoberfest`](https://github.com/vatsalsinghkv/easy-fix/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Ahacktoberfest). I can create a textbox that filters the content as so

I have a lot of experience working with React and TailwindCSS frontends, here are a few examples ([1](https://github.com/newtoallofthis123/About), [2])(https://github.com/newtoallofthis123/ReactSite), [3](https://github.com/newtoallofthis123/clicky))

I got the repo working locally and have gone through the codebase and understood it. I believe I can get this done. 
I will not change any of the existing codebase and everything would be done using well documented commits and comments. Everything will also be well tested before committing.

Please assign this issue to me for Hacktober Fest. 

### ✨ Browser

Brave

### Checklist 🚀

- [X] I checked and didn't find similar [issue](https://github.com/vatsalsinghkv/easy-fix/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/vatsalsinghkv/easy-fix/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no).

**Comment by vatsalsinghkv** [comment]
Hey @newtoallofthis123, I've assigned this issue to you. About the filtering by user I am not sure if that would be easily achievable we tried something like that but couldn't succeed because of the limitation of the github's particular api that we are using here. I am sure you can check the api in the `config` file.

Under this issue I want you to add this feature: Filter by labels like `hacktoberfest`, right now we are using combinations of `easy`, `first`, `good` keywords for the label.

For the testing, test it by checking if the app fetches the latest issues instead of old ones for each filter.

And also join the discord for this project for communication, where you can even discuss the progress, issues and more features. Discord: https://discord.gg/St2dHg9YwA

**Comment by newtoallofthis123** [comment]
I'll look into the user aspect of it. Thanks. Will join the discord and start working on it

**Comment by vatsalsinghkv** [comment]
Make sure you make PR after 1st of October.

**Comment by vatsalsinghkv** [comment]
@newtoallofthis123 Hey bro how's the progress?

**Comment by newtoallofthis123** [comment]
Going quite well.....i was able to get in more languages and custom language searching,

Other than that, I am struggling a bit with custom filtering like you said 😅...will figure it out

**Comment by vatsalsinghkv** [comment]
@newtoallofthis123 if you get stuck or need help you can always reach out to me ✨. The important feature is able to search issue by labels like `hacktoberfest`

**Comment by newtoallofthis123** [comment]
Oh right! Hadn't realised that....will concentrate on that a bit more

**Comment by vatsalsinghkv** [comment]
@newtoallofthis123 no problem just let me know if you need any help its an easy issue you can easily implement the feature for searching issue by level by just configuring request api

**Comment by vatsalsinghkv** [comment]
@newtoallofthis123 Hey Ishan, how's it going? the functionality of fetching issues by label? Any issues?

**Comment by vatsalsinghkv** [comment]
### We need have labels like this
![](https://user-images.githubusercontent.com/68834718/275252109-23163563-8924-4465-a7a7-73aa9711f850.png)

**Comment by newtoallofthis123** [comment]
Oh! Okay
