### ISSUE TITLE
To add the social media icons of the website admin in the footer

### ISSUE THREAD

**Issue by Rohansaini1512** [vatsalsinghkv/easy-fix#34]
### Description

To add the icons like linkedin , twitter ( x ), and github in the footer section of the website

### ✨ Browser

Brave

### Checklist 🚀

- [X] I checked and didn't find similar [issue](https://github.com/vatsalsinghkv/easy-fix/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/vatsalsinghkv/easy-fix/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no).

**Comment by Rohansaini1512** [comment]
@vatsalsinghkv pls. assign this issue to me under Hacktoberfest . My approach will be using react-icons to do so.

**Comment by Rohansaini1512** [comment]
@vatsalsinghkv  shall I start working on this ?

**Comment by vatsalsinghkv** [comment]
@Rohansaini1512 is this issue similar to #12 ?
