### ISSUE TITLE
[FEATURE] Improve context provider

### ISSUE THREAD

**Issue by fekete965** [vatsalsinghkv/easy-fix#35]
### Description

I would like to propose improving the `UseUrlProvider`.
I would make the following changes:

1. Rename `UseUrlProvider` to `UrlProvider` as this is not a hook but a context provider hence no need to add `use` at the beginning
2. Move this file to a `context` folder
3. Migrate the provider to TS
4. Make the related hook(s) safer

### ✨ Browser

Brave

### Checklist 🚀

- [X] I checked and didn't find similar [issue](https://github.com/vatsalsinghkv/easy-fix/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/vatsalsinghkv/easy-fix/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no).

**Comment by fekete965** [comment]
@vatsalsinghkv would you be able to mark it under hacktoberfest, please? 🙏

**Comment by fekete965** [comment]
@vatsalsinghkv are you happy with me to proceed with this? Would you be able to tag this issue as well?

**Comment by vatsalsinghkv** [comment]
@fekete965 sure brother, sorry for the delay

**Comment by fekete965** [comment]
> @fekete965 sure brother, sorry for the delay

Thanks a lot. :)
Link to the PR: https://github.com/vatsalsinghkv/easy-fix/pull/49
