### ISSUE TITLE
[FEATURE] Migrate lib folder to TS

### ISSUE THREAD

**Issue by fekete965** [vatsalsinghkv/easy-fix#36]
### Description

Migrate `/lib` folder to TS

### ✨ Browser

Brave

### Checklist 🚀

- [X] I checked and didn't find similar [issue](https://github.com/vatsalsinghkv/easy-fix/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/vatsalsinghkv/easy-fix/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no).

**Comment by vatsalsinghkv** [comment]
@fekete965 Migrate `lib/` folder?

**Comment by fekete965** [comment]
@vatsalsinghkv very well then. I'll update the issue :)

**Comment by fekete965** [comment]
I will start the work this weekend. Please note, that anything merged during this process could prolong the work.
I don't believe this would be an issue, just wanted to point this out.
