### ISSUE TITLE
[BUG]  API throwing 401 error

### ISSUE THREAD

**Issue by premtw** [vatsalsinghkv/easy-fix#37]
### Description

APIs used to get the issues are throwing the 401 Bad Credentials error.

### Screenshots

<img width="791" alt="image" src="https://github.com/vatsalsinghkv/easy-fix/assets/102960817/fb333822-7245-47ce-b70d-7939d6084df8">

### ✨ Browser

Google Chrome

### Checklist 🚀

- [X] I checked and didn't find similar [issue](https://github.com/vatsalsinghkv/easy-fix/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/vatsalsinghkv/easy-fix/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no).

**Comment by fekete965** [comment]
Could you write down how to reproduce the problem? 🤔

**Comment by vatsalsinghkv** [comment]
@fekete965 @premtw I think I've fixed it check again

**Comment by premtw** [comment]
@vatsalsinghkv Cross verified it and it is not an issue. The Readme has to be updated with the instructions to setup the Github API token.  Updating the readme will comes under the part of Documentation. Shall we close this issue and create new one for the Documentation update?

**Comment by vatsalsinghkv** [comment]
@premtw sure update it, can you help me with the vercel thing, like after adding env variable in vercel it doesn't deploy the PR without my approval, do you know how can I change it?

**Comment by premtw** [comment]
@vatsalsinghkv  Sure, will update the Readme. I didn't work in the vercel but will do my research on the same.
