### ISSUE TITLE
[BUG] Pagination doesn't work for more than 1 sibling buttons

### ISSUE THREAD

**Issue by vatsalsinghkv** [vatsalsinghkv/easy-fix#4]
### Issue
Pagination works when we have  set 0 or 1 `TOTAL_SIBLING_BUTTONS`. 

Like for `0` it shows pagination as **1... 5 (selected)... last btn**
Like for `1` it shows pagination as **1... 4, 5 (selected), 6... last btn**
But for `2` it shoes pagination as **1... 3, 5 (selcted), 7... last btn**. (it missed 4 and 6 page button).

### Steps to Solve it

- Change the `TOTAL_SIBLING_BUTTONS` buttons by editing `src/utils/config.js` to generate the error.
- You need to check the logic and refine it in `src/components/PaginationButton.jsx`.
- You can test it out by running `yarn test:watch` and changing `TOTAL_SIBLING_BUTTONS` value

### Screenshots

- #### ❌ TOTAL_SIBLING_BUTTONS = 2
<img width="917" alt="Screenshot 2023-09-27 at 12 13 03 PM" src="https://github.com/vatsalsinghkv/easy-fix/assets/68834718/43845cf4-1140-4ce5-ab8f-53727bdf011a">
Buttons Missing 4 & 6

- #### ✅ TOTAL_SIBLING_BUTTONS = 1
<img width="907" alt="Screenshot 2023-09-27 at 12 14 42 PM" src="https://github.com/vatsalsinghkv/easy-fix/assets/68834718/bfa808a4-2141-4cf6-a8b4-21532a2c5900">

### ✨ Browser

Google Chrome

### Checklist 🚀

- [X] I checked and didn't find similar [issue](https://github.com/vatsalsinghkv/easy-fix/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/vatsalsinghkv/easy-fix/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (blank for no).

**Comment by IIB3nceII** [comment]
I would like to work on this issue

**Comment by ChavvaNarayana** [comment]
Sounds good to me. I'm willing to contribute.
Please assign it to me.

**Comment by premtw** [comment]
@vatsalsinghkv Please assign to me. I like to contribute to this

**Comment by vatsalsinghkv** [comment]
Hey @IIB3nceII , I have assigned you the issue. Feel free to ping me on [Discord](https://discord.gg/NKp5ZrjJej) if you've got any issue or suggestion. 

Happy Hacking ✨

**Comment by IIB3nceII** [comment]
Unassigned by mistake, please ressign to me. Here is the pr:
https://github.com/vatsalsinghkv/easy-fix/pull/13
