### ISSUE TITLE
[FEATURE] Improve use-fetch hook

### ISSUE THREAD

**Issue by fekete965** [vatsalsinghkv/easy-fix#43]
### Description

The following hook is not very versatile.
I would improve the API to the following:
1. It would take in a function that returns a promise () => Promise<T>
2. A reducer would be used to avoid state unnecessary batching
3. The return value would be the following: `data: T | null`, `error: RequestError` (will be defined as a model), `status: RequestStatus` (will be defined as a model), `isLoading: boolean`, `hasError: boolean`, `run: () => Promise<void>

The API might change, I will keep this issue updated.

### ✨ Browser

Google Chrome

### Checklist 🚀

- [X] I checked and didn't find similar [issue](https://github.com/vatsalsinghkv/easy-fix/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/vatsalsinghkv/easy-fix/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no).

**Comment by vatsalsinghkv** [comment]
@fekete965 can you elaborate it I didn't get the taking a function type?

I think it's way more easier than passing url for fetching the data, we can even pass an additional options object for headers

I think we can really improve it if we use one state `status: 'loading' | 'error' | 'success'` instead of isLoading and error values, we can use the TS to make the return type as: if `status === 'error'` the `error: Error | string`

**Comment by fekete965** [comment]
> @fekete965 can you elaborate it I didn't get the taking a function type?
> 
> I think it's way more easier than passing url for fetching the data, we can even pass an additional options object for headers
> 
> I think we can really improve it if we use one state `status: 'loading' | 'error' | 'success'` instead of isLoading and error values, we can use the TS to make the return type as: if `status === 'error'` the `error: Error | string`

So the hook would take in a function which returns a Promise<T>.
The returned `run` value is a function that invokes the promise and populates the state.

This allows the hook to be widely used as it gives the developer full control over what is getting passed in. (inversion of control)

The type narrowing was planned using the status property. :) It is a nice touch.
