### ISSUE TITLE
[FEATURE] Add contributors profiles in Readme

### ISSUE THREAD

**Issue by vatsalsinghkv** [vatsalsinghkv/easy-fix#46]
### Description

We can add a section in README thanking contributors and showing their profile

### ✨ Browser

Google Chrome

### Checklist 🚀

- [X] I checked and didn't find similar [issue](https://github.com/vatsalsinghkv/easy-fix/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/vatsalsinghkv/easy-fix/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (blank for no).

**Comment by Pinaka-Pani-18** [comment]
Hi, can I work on this issue ?
