### ISSUE TITLE
[FEATURE] Write unit tests for component testing.

### ISSUE THREAD

**Issue by vatsalsinghkv** [vatsalsinghkv/easy-fix#6]
### Description

Need to write needed test-cases and tests in Vitest

### Something like this

<img width="1377" alt="Screenshot 2023-09-28 at 9 38 02 PM" src="https://github.com/vatsalsinghkv/easy-fix/assets/68834718/c1acd98f-a6c3-4b14-8f8a-510309e7e686">

### ✨ Browser

Google Chrome

### Checklist 🚀

- [X] I checked and didn't find similar [issue](https://github.com/vatsalsinghkv/easy-fix/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/vatsalsinghkv/easy-fix/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (blank for no).

**Comment by josediego** [comment]
Can I work on this one, please? :)

**Comment by josediego** [comment]
Hey @vatsalsinghkv, just a quick update

I've completed writing all the tests possible for the project and have also added coverage tracking (you can check it out here: [coverage](https://vitest.dev/guide/features.html#coverage)) to give us a clearer picture of our app's testing status.

Here's an example of one of the tests running on my local setup:

![Test Example](https://github.com/vatsalsinghkv/easy-fix/assets/5665920/5ab234af-a213-46a8-a405-2bfead0ce7fa)

Would it be alright with you if I create the pull request on October 1st? This way, I can make a valid contribution to Hacktoberfest. 

Let me know your thoughts! 😊

**Comment by vatsalsinghkv** [comment]
@josediego I am really impressed with ur work. Yea sure feel free to do that. I couldn't understand much about the coverage can you explain me about this in the simplest words?

**Comment by josediego** [comment]
Certainly! Code coverage is like a tool that tells you how much of your code is tested when you run automatic tests. It helps you see if your tests are good enough and if they really check the parts of the program they are meant to check.
