### ISSUE TITLE
[FEATURE] Add CI tool to auto label the PR.

### ISSUE THREAD

**Issue by vatsalsinghkv** [vatsalsinghkv/easy-fix#68]
### Description

Add Github action to auto-label the PR according to its status and content

### ✨ Browser

Google Chrome

### Checklist 🚀

- [X] I checked and didn't find similar [issue](https://github.com/vatsalsinghkv/easy-fix/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/vatsalsinghkv/easy-fix/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (blank for no).

**Comment by Vai-Man** [comment]
Can I work on it?

**Comment by vatsalsinghkv** [comment]
@Vai-Man sure. you need to add github actions

**Comment by Vai-Man** [comment]
@vatsalsinghkv Implemented the feature thru #74

**Comment by vatsalsinghkv** [comment]
@Vai-Man amazing work man, thanks ☺️
