### ISSUE TITLE
[FEATURE]: Option to add custom labels.

### ISSUE THREAD

**Issue by kushchoudhary98** [vatsalsinghkv/easy-fix#72]
### Description

There should be an option to add our custom labels, in case the user want to search for some other label.

### Screenshots
![Screenshot 2024-10-20 at 3 41 37 PM](https://github.com/user-attachments/assets/af6401ad-1804-47c1-b1f9-ad25a844aea5)

### ✨ Browser

Safari

### Checklist 🚀

- [X] I checked and didn't find similar [issue](https://github.com/vatsalsinghkv/easy-fix/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/vatsalsinghkv/easy-fix/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no).

**Comment by vatsalsinghkv** [comment]
Thats so thought full. Thanks
