### ISSUE TITLE
[FEATURE] Add a Buttons and labels as Beginner Friendly  , Medium  and Advance issue 

### ISSUE THREAD

**Issue by Aniket-2504** [vatsalsinghkv/easy-fix#76]
### ✨ Browser

Google Chrome

### Checklist 🚀

- [X] I checked and didn't find similar [issue](https://github.com/vatsalsinghkv/easy-fix/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/vatsalsinghkv/easy-fix/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no).

**Comment by vatsalsinghkv** [comment]
@Aniket-2504 lets say we have added these buttons how do we define a issue if it's a beginner friendly or advanced or hard?
