### ISSUE TITLE
[FEATURE] Add few more programming languages to the list

### ISSUE THREAD

**Issue by abhirajadhikary06** [vatsalsinghkv/easy-fix#77]
### Description

Permission to add few more programming langues to the list shown in the Screen shot.

### Screenshots

![image](https://github.com/user-attachments/assets/2deab0f8-bfc1-4dc9-9824-584ff6d12866)

### ✨ Browser

Google Chrome

### Checklist 🚀

- [X] I checked and didn't find similar [issue](https://github.com/vatsalsinghkv/easy-fix/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/vatsalsinghkv/easy-fix/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no).

**Comment by vatsalsinghkv** [comment]
@abhirajadhikary06  which one you prefer, whenever you add a language to the list, make sure that  when you fetch the issues for that language the fresh issues are fetched if outdates issues are being fetched then there's no need for that particular language

**Comment by abhirajadhikary06** [comment]
I am willing to add 'C' as one of the programming language.
