### ISSUE TITLE
[FEATURE] Option to Sort the issues

### ISSUE THREAD

**Issue by vatsalsinghkv** [vatsalsinghkv/easy-fix#8]
### Description

Just like the filter category, a sorting category is also needed which would have the functionality to sort the issue by time  (last created or last updated) and by stars can also add []. 

Can also add the functionality of sorting by ascending and descending. By default sorting should be done by time.

Resources:
- https://docs.github.com/en/rest/search/search?apiVersion=2022-11-28#search-issues-and-pull-requests

### Something like this: 
<img width="355" alt="Screenshot 2023-09-30 at 12 32 42 AM" src="https://github.com/vatsalsinghkv/easy-fix/assets/68834718/aeaadbb2-fa40-4427-81f3-3412967ff69a">

### Design Inspiration
<img width="131" alt="Screenshot 2023-09-30 at 12 27 20 AM" src="https://github.com/vatsalsinghkv/easy-fix/assets/68834718/84d6f689-bb03-47e3-b833-3b997755c4fc">

### ✨ Browser

Google Chrome

### Checklist 🚀

- [X] I checked and didn't find similar [issue](https://github.com/vatsalsinghkv/easy-fix/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/vatsalsinghkv/easy-fix/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (blank for no).

**Comment by premtw** [comment]
Hi @vatsalsinghkv 
   I like to contribute to this feature. Please assign to me

**Comment by S4JN** [comment]
I would like to add this feature

**Comment by premtw** [comment]
Created the PR for the same
https://github.com/vatsalsinghkv/easy-fix/pull/19
