### ISSUE TITLE
[FEATURE] Save filters settings in the local-storage

### ISSUE THREAD

**Issue by vatsalsinghkv** [vatsalsinghkv/easy-fix#82]
### Description

Right now whenever we refresh the app the filter settings got reset.
So add the functionality to save the user preferred filter settings to the local-storage and load settings from there.

STEPS:
create a global hook useLocalStorage and use it to save and load filters settings

### ✨ Browser

Google Chrome

### Checklist 🚀

- [X] I checked and didn't find similar [issue](https://github.com/vatsalsinghkv/easy-fix/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/vatsalsinghkv/easy-fix/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (blank for no).

**Comment by PAVAN507-STAR** [comment]
Hii @vatsalsinghkv .I would like to work on this issue.Can u assign this issue to me?

**Comment by vatsalsinghkv** [comment]
@PAVAN507-STAR still wanna work?
