### ISSUE TITLE
[FEATURE] Show number of conversations in the issue

### ISSUE THREAD

**Issue by vatsalsinghkv** [vatsalsinghkv/easy-fix#9]
### Description

Show the no. of conversations or activity in the issue, so user can get the idea of the activity of the issue.

Resource: 
- https://docs.github.com/en/rest/search/search?apiVersion=2022-11-28#search-issues-and-pull-requests

### UI can be something like
just before stars, feel free to improve the UI
<img width="916" alt="Screenshot 2023-09-30 at 12 48 21 AM" src="https://github.com/vatsalsinghkv/easy-fix/assets/68834718/9ad84bb8-58b6-42b6-890a-5adc459fd01d">

### ✨ Browser

Google Chrome

### Checklist 🚀

- [X] I checked and didn't find similar [issue](https://github.com/vatsalsinghkv/easy-fix/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/vatsalsinghkv/easy-fix/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (blank for no).

**Comment by VaibhavKVerma** [comment]
Hey @vatsalsinghkv can you assign this issue to me?

**Comment by cd-ramesh** [comment]
@vatsalsinghkv can you assign me this issue?

**Comment by Ratikant-rout** [comment]
Hello @vatsalsinghkv brother i want to contribute my first project in your Repo can You please Assing me this repo i will me so much glas to work upon it.

**Comment by yashmangal112** [comment]
Hello @vatsalsinghkv please assign this issue to me

**Comment by vatsalsinghkv** [comment]
@yashmangal112 how's the progress

**Comment by rishuxd** [comment]
Hey @vatsalsinghkv, I've given it a try. The question is: should I display it even if there are no comments on the issue, or should I turn it off?

**Comment by rishuxd** [comment]
> Hey @vatsalsinghkv, I've given it a try. The question is: should I display it even if there are no comments on the issue, or should I turn it off?

This is how it looks for now.
![image](https://github.com/vatsalsinghkv/easy-fix/assets/96189271/01e914a2-e07e-45a5-896c-5dc5cdd7579a)

**Comment by vatsalsinghkv** [comment]
@rishuxd tou can either show 0 it'd be better

**Comment by rishuxd** [comment]
Hey @vatsalsinghkv, I have raised the PR, please check it out!
